<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <Compile Remove="Models\**" />
    <EmbeddedResource Remove="Models\**" />
    <None Remove="Models\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Pedagogico.Domain\Lingol.Pedagogico.Domain\Lingol.Pedagogico.Domain.csproj" />
    <ProjectReference Include="..\..\..\..\BuildingBlocks\Lingol.Contracts\Lingol.Contracts\Lingol.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="14.2.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
